apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-portal
  labels:
    app: retail-portal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: retail-portal
  template:
    metadata:
      labels:
        app: retail-portal
    spec:
      serviceAccountName: retail-portal
      containers:
        - name: retail-portal
          image: IMAGE_URI_PLACEHOLDER
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
            - name: metrics
              containerPort: 9404
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 45
            periodSeconds: 20
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: retail-portal
