apiVersion: v1
kind: Service
metadata:
  name: retail-portal
  labels:
    app: retail-portal
spec:
  type: LoadBalancer
  selector:
    app: retail-portal
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: metrics
      port: 9404
      targetPort: 9404
